version: '3.8'

services:
  webapi:
    image: desafionubimetrics-webapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
